[WFLY-13351] Galleon layer for the Mail subsystem
wildfly/wildfly-proposals pull request #308
Opened 2020-04-27 16:34 UTC by yersan

Jira issue: https://issues.redhat.com/browse/WFLY-13351

2020-07-31 17:04 UTC, darranl commented
For all new layers I think we need to make sure security is considered in the requirements,

We don't want to accidentally leave anything unsecured by default but ideally if layers can avoid a dependency on any security layers that would be preferred.

Failing that for the new layers if security dependencies are required we should be preferring elytron with an option to select legacy security.  At some point in the future all legacy security related layers will be removed.

Can we please add a check for these questions in the requirements?

2020-09-10 13:01 UTC, fabiobrz requested changes
Hi @yersan - thanks for this proposal. I dropped just one comment, let me know what you think.

2020-09-10 14:43 UTC, yersan commented on mail/WFLY-13351_galleon_layer_for_mail_subsystem.adoc
> +* The Galleon layer must provide the basic configuration Mail subsystem configuration.
@fabiobrz I've just fixed the wording here.

2020-09-10 14:44 UTC, yersan commented
> For all new layers I think we need to make sure security is considered in the requirements,
> 
> We don't want to accidentally leave anything unsecured by default but ideally if layers can avoid a dependency on any security layers that would be preferred.
> 
> Failing that for the new layers if security dependencies are required we should be preferring elytron with an option to select legacy security. At some point in the future all legacy security related layers will be removed.
> 
> Can we please add a check for these questions in the requirements?

I've just added a note in the requirements section specifying this Galleon layer will not depend upon a security layer

2020-09-10 14:45 UTC, fabiobrz approved these changes

2020-09-15 01:51 UTC, merged