Test plan
wildfly/wildfly-proposals pull request #589
Opened 2024-07-23 11:29 UTC by luck3y

F2F: WildFly Community Feature Test Plan

Note this is an initial draft for these changes, wider input is more than welcome!

FYI: @yersan @OndrejKotek @ehsavoie

2024-07-23 11:34 UTC, OndrejKotek commented on design-doc-template.adoc
> +*** Unit / Integration tests: Manual checks for significant changes in server performance, memory and disk footprint should be described here. These checks are not always relevant, but consideration
"Unit / Integration tests" -> "Miscellaneous checks" ?

2024-07-23 11:49 UTC, ehsavoie approved these changes

2024-07-23 12:06 UTC, luck3y commented
FYI: @darranl @bstansberry @jmesnil

2024-08-14 14:03 UTC, luck3y commented
Note, converted from draft as there appears to be no more changes and a reminder to all to have a look.

2024-08-15 09:15 UTC, OndrejKotek approved these changes

2024-08-16 14:00 UTC, yersan approved these changes

2024-09-12 16:32 UTC, bstansberry requested changes

2024-09-12 16:32 UTC, bstansberry commented on design-doc-template.adoc
> +** Experimental - no test plan is required. Unit / integration tests may still be added as needed during development.
s/may/should

2024-09-12 16:32 UTC, bstansberry commented on design-doc-template.adoc
> +** Experimental - no test plan is required. Unit / integration tests may still be added as needed during development.
Perhaps

"Basic unit / integration tests should be added during development."

IOW people should write some tests but we're not going to be prescriptive about the details.

2024-09-16 15:55 UTC, luck3y commented
@bstansberry I've been out for a couple of days, catching up now, will mail the list and solicit feedback etc.

2024-09-22 01:11 UTC, bstansberry approved these changes

2024-09-22 01:11 UTC, merged

2024-09-22 01:11 UTC, bstansberry commented
Thanks @luck3y