[WFCORE-6960]: Promote Simple config export for a server as an attachment from COMMUNITY to DEFAULT.
wildfly/wildfly-proposals pull request #594
Opened 2024-08-28 09:39 UTC by ehsavoie

Jira: https://issues.redhat.com/browse/WFCORE-6960

2024-08-29 12:37 UTC, fabiobrz requested changes
Thanks for this proposal @ehsavoie - I dropped some comments, feel free to let me know what you think.

2024-08-29 13:16 UTC, ehsavoie commented on core/WFCORE-6960_Simple_config_export_for_a_server_as_an_attachment_for_standalone_or_domain_mode.adoc
> +To display the content of the file:
yes

2024-08-29 13:16 UTC, ehsavoie commented on core/WFCORE-6960_Simple_config_export_for_a_server_as_an_attachment_for_standalone_or_domain_mode.adoc
> +* Covered by operation description in management model.
read-operation-description(name=read-config-as-xml-file)

2024-08-30 09:27 UTC, fabiobrz commented on core/WFCORE-6960_Simple_config_export_for_a_server_as_an_attachment_for_standalone_or_domain_mode.adoc
> +The purpose of this feature is to enrich the management model with a new operation *read-config-as-xml-file* equivalent to the existing *read-config-as-xml" that would return a stream to be either di
Nitpicking I know, but there's a minor typo here: s/`*read-config-as-xml"`/`*read-config-as-xml*`/

2024-08-30 09:27 UTC, fabiobrz commented on core/WFCORE-6960_Simple_config_export_for_a_server_as_an_attachment_for_standalone_or_domain_mode.adoc
> +* Create a new management operation that takes the result of the marshalling done in *read-config-as-xml* and but it is a stream instead of a String.
Maybe a typo here? I can't understand the following:
```
and but it is a stream instead of a String
```

2024-08-30 09:27 UTC, fabiobrz commented on core/WFCORE-6960_Simple_config_export_for_a_server_as_an_attachment_for_standalone_or_domain_mode.adoc
> +* Covered by operation description in management model.
Sorry, but this is not enough.
The community documentation is properly documenting `read-config-as-xml`:
- https://docs.wildfly.org/33/Admin_Guide.html#operations
- https://docs.wildfly.org/33/Admin_Guide.html#view-configuration-as-xml-for-domain-model-or-host-model
 so this new operation must be documented as well in there, and mentioned here in the analysis document.
You can add the changes to the documentation either in your latest feature implementation PR, or in a separate one, and link it to https://issues.redhat.com/browse/WFCORE-6960

2024-08-30 09:27 UTC, fabiobrz commented on core/WFCORE-6960_Simple_config_export_for_a_server_as_an_attachment_for_standalone_or_domain_mode.adoc
> +Simple usage:
If you're okay with the change you added, then you can resolve this comment. I just noticed I don't have the "Resolve" button available here, thanks.

2024-08-30 09:29 UTC, fabiobrz requested changes
Thanks for addressing my remarks @ehsavoie - I've left a couple more comments.

2024-09-01 15:55 UTC, fabiobrz commented on core/WFCORE-6960_Simple_config_export_for_a_server_as_an_attachment_for_standalone_or_domain_mode.adoc
> +* Covered by operation description in management model.
Tracked by https://github.com/wildfly/wildfly/pull/18159

2024-09-01 16:01 UTC, fabiobrz requested changes
Still 2 minor typos...

2024-09-01 16:01 UTC, fabiobrz commented on core/WFCORE-6960_Simple_config_export_for_a_server_as_an_attachment_for_standalone_or_domain_mode.adoc
> +The purpose of this feature is to enrich the management model with a new operation *read-config-as-xml-file* equivalent to the existing *read-config-as-xml" that would return a stream to be either di
Thanks, can be resolved.

2024-09-02 08:27 UTC, fabiobrz approved these changes
Thanks @ehsavoie for your work on this proposal. Changes LGTM, approving.

2024-09-13 13:15 UTC, emmartins commented
Hi @ehsavoie , can you please add the information wrt the following sections:

*Backwards Compatibility
**Default Configuration
**Importing Existing Configuration
*Deployments

Even if empty, those sections are now used by Migration Feature team to figure out which feature teams are doing migration related changes, so we may help them.

2024-09-16 07:07 UTC, ehsavoie commented
@emmartins all should be addressed

2024-09-19 12:57 UTC, merged