[WFLY-19835] Integrate OpenTracing with MicroProfile Reactive Messagi…
wildfly/wildfly-proposals pull request #638
Opened 2024-10-18 15:32 UTC by kabir

…ng Kafka Connector

https://issues.redhat.com/browse/WFLY-19835

2024-10-23 08:35 UTC, rhusar requested changes

2024-10-23 08:35 UTC, rhusar commented on microprofile/WFLY-19835_microprofile_reactive_messaging_otel_with_kafka.adoc
> +* `ALWAYS` - `mp.messaging.connector.smallrye-{connector-lower}.tracing-enabled` is forced to be `true` in such a way that user's MicroProfile Config properties can never set it to `false`
FYI the rendering here is fracked up, you need an empty line before a list.

2024-11-12 23:11 UTC, bstansberry commented on microprofile/WFLY-19835_microprofile_reactive_messaging_otel_with_kafka.adoc
> +* Traditional standalone server (unzipped or provisioned by Galleon)
Why not managed domain?

EAP XP doesn't support domain mode, but that is not due to any fundamental technical limitations. And this is WildFly functionality / a WildFly proposal and AFAIK there's no reason this wouldn't work. The relevant extensions are all supported in WildFly domain mode.

https://github.com/wildfly/wildfly/blob/main/galleon-pack/galleon-feature-pack/wildfly-feature-pack-build.xml#L93-L107

2024-11-25 14:03 UTC, istraka requested changes

2024-11-25 14:03 UTC, istraka commented on microprofile/WFLY-19835_microprofile_reactive_messaging_otel_with_kafka.adoc
> +The MicroProfile Config properties in the  link:#Overview[Overview], are all booleans, and the values have these meanings:
@kabir can you add requirements for channels, connectors and the order of resolution fo the final value like in https://github.com/wildfly/wildfly/pull/18320/files#diff-cb0945fc010a25c215e621bb884a50a79cce48b93356cc7679642ca0364cd00cR399-R410, please?

2024-12-11 11:57 UTC, merged